version: "3.3"

services:
  db:
    image: postgres:12.3-alpine
    ports:
      - "5678:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=feeder
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "feeder" ]
      interval: 10s
      timeout: 5s
      retries: 5
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    links:
      - "db:database"
    environment:
      - DB_NAME=feeder
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=feeder.settings.production
      - SECRET_KEY=django-insecure-f00r*pf@%#^^k=jnah3*n(!zniam9&@nj$may-9*w=p(hvnv*s
      - ALLOWED_HOSTS=0.0.0.0

volumes:
  postgres_data:
