# Generated by Django 3.2.13 on 2022-06-20 16:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("feed", "0002_auto_20220620_1542"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollowfeed",
            unique_together={("user", "feed")},
        ),
    ]
