# Generated by Django 3.2.13 on 2022-06-20 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_alter_userfollowfeed_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbookmarknews',
            unique_together={('user', 'news')},
        ),
        migrations.AlterUniqueTogether(
            name='userfavoritenews',
            unique_together={('user', 'news')},
        ),
        migrations.AlterUniqueTogether(
            name='userreadnews',
            unique_together={('user', 'news')},
        ),
    ]
